// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LinuxGUITest {
    
    
    public partial class BalanceBoardInformation {
        
        private Gtk.Action BalanceBoardAction;
        
        private Gtk.Action DisconnectAction;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.HBox hbox4;
        
        private Gtk.CheckButton checkboxLed;
        
        private Gtk.Label lblButton;
        
        private Gtk.Entry entryButton;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Table table4;
        
        private Gtk.Entry entryBottomLeft;
        
        private Gtk.Entry entryBottomRight;
        
        private Gtk.Entry entryTopLeft;
        
        private Gtk.Entry entryTopRight;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label lblTotalWeight;
        
        private Gtk.Entry entryTotalWeight;
        
        private Gtk.Entry entryAverageWeight;
        
        private Gtk.Label labelAverageWeight;
        
        private Gtk.Label GtkLabel2;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.DrawingArea drawingareaBalance;
        
        private Gtk.Label GtkLabel3;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Button btnUpdateBattery;
        
        private Gtk.ProgressBar progressbar1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LinuxGUITest.BalanceBoardInformation
            Stetic.BinContainer w1 = Stetic.BinContainer.Attach(this);
            Gtk.UIManager w2 = new Gtk.UIManager();
            Gtk.ActionGroup w3 = new Gtk.ActionGroup("Default");
            this.BalanceBoardAction = new Gtk.Action("BalanceBoardAction", Mono.Unix.Catalog.GetString("BalanceBoard"), null, null);
            this.BalanceBoardAction.ShortLabel = Mono.Unix.Catalog.GetString("BalanceBoard");
            w3.Add(this.BalanceBoardAction, null);
            this.DisconnectAction = new Gtk.Action("DisconnectAction", Mono.Unix.Catalog.GetString("Disconnect"), null, null);
            this.DisconnectAction.ShortLabel = Mono.Unix.Catalog.GetString("Disconnect");
            w3.Add(this.DisconnectAction, null);
            w2.InsertActionGroup(w3, 0);
            this.Name = "LinuxGUITest.BalanceBoardInformation";
            // Container child LinuxGUITest.BalanceBoardInformation.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            w2.AddUiFromString("<ui><menubar name='menubar1'><menu action='BalanceBoardAction'><menuitem action='DisconnectAction'/></menu></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(w2.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox1.Add(this.menubar1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.vbox1.Add(this.hseparator2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.hseparator2]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.checkboxLed = new Gtk.CheckButton();
            this.checkboxLed.CanFocus = true;
            this.checkboxLed.Name = "checkboxLed";
            this.checkboxLed.Label = Mono.Unix.Catalog.GetString("Led");
            this.checkboxLed.DrawIndicator = true;
            this.checkboxLed.UseUnderline = true;
            this.hbox4.Add(this.checkboxLed);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox4[this.checkboxLed]));
            w6.Position = 0;
            // Container child hbox4.Gtk.Box+BoxChild
            this.lblButton = new Gtk.Label();
            this.lblButton.Name = "lblButton";
            this.lblButton.LabelProp = Mono.Unix.Catalog.GetString("Button");
            this.hbox4.Add(this.lblButton);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox4[this.lblButton]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.entryButton = new Gtk.Entry();
            this.entryButton.CanFocus = true;
            this.entryButton.Name = "entryButton";
            this.entryButton.IsEditable = false;
            this.entryButton.InvisibleChar = '●';
            this.hbox4.Add(this.entryButton);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox4[this.entryButton]));
            w8.Position = 2;
            this.vbox1.Add(this.hbox4);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
            w9.Position = 2;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.table4 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table4.Name = "table4";
            this.table4.RowSpacing = ((uint)(6));
            this.table4.ColumnSpacing = ((uint)(6));
            // Container child table4.Gtk.Table+TableChild
            this.entryBottomLeft = new Gtk.Entry();
            this.entryBottomLeft.CanFocus = true;
            this.entryBottomLeft.Name = "entryBottomLeft";
            this.entryBottomLeft.IsEditable = false;
            this.entryBottomLeft.InvisibleChar = '●';
            this.table4.Add(this.entryBottomLeft);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table4[this.entryBottomLeft]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.entryBottomRight = new Gtk.Entry();
            this.entryBottomRight.CanFocus = true;
            this.entryBottomRight.Name = "entryBottomRight";
            this.entryBottomRight.IsEditable = false;
            this.entryBottomRight.InvisibleChar = '●';
            this.table4.Add(this.entryBottomRight);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table4[this.entryBottomRight]));
            w11.TopAttach = ((uint)(1));
            w11.BottomAttach = ((uint)(2));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.entryTopLeft = new Gtk.Entry();
            this.entryTopLeft.CanFocus = true;
            this.entryTopLeft.Name = "entryTopLeft";
            this.entryTopLeft.IsEditable = false;
            this.entryTopLeft.InvisibleChar = '●';
            this.table4.Add(this.entryTopLeft);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table4[this.entryTopLeft]));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.entryTopRight = new Gtk.Entry();
            this.entryTopRight.CanFocus = true;
            this.entryTopRight.Name = "entryTopRight";
            this.entryTopRight.IsEditable = false;
            this.entryTopRight.InvisibleChar = '●';
            this.table4.Add(this.entryTopRight);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table4[this.entryTopRight]));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(2));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox3.Add(this.table4);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox3[this.table4]));
            w14.Position = 0;
            w14.Expand = false;
            w14.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.lblTotalWeight = new Gtk.Label();
            this.lblTotalWeight.Name = "lblTotalWeight";
            this.lblTotalWeight.LabelProp = Mono.Unix.Catalog.GetString("Total Weight");
            this.hbox3.Add(this.lblTotalWeight);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox3[this.lblTotalWeight]));
            w15.Position = 0;
            w15.Expand = false;
            w15.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.entryTotalWeight = new Gtk.Entry();
            this.entryTotalWeight.CanFocus = true;
            this.entryTotalWeight.Name = "entryTotalWeight";
            this.entryTotalWeight.IsEditable = false;
            this.entryTotalWeight.InvisibleChar = '●';
            this.hbox3.Add(this.entryTotalWeight);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox3[this.entryTotalWeight]));
            w16.Position = 1;
            // Container child hbox3.Gtk.Box+BoxChild
            this.entryAverageWeight = new Gtk.Entry();
            this.entryAverageWeight.CanFocus = true;
            this.entryAverageWeight.Name = "entryAverageWeight";
            this.entryAverageWeight.IsEditable = false;
            this.entryAverageWeight.InvisibleChar = '●';
            this.hbox3.Add(this.entryAverageWeight);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox3[this.entryAverageWeight]));
            w17.PackType = ((Gtk.PackType)(1));
            w17.Position = 2;
            // Container child hbox3.Gtk.Box+BoxChild
            this.labelAverageWeight = new Gtk.Label();
            this.labelAverageWeight.Name = "labelAverageWeight";
            this.labelAverageWeight.LabelProp = Mono.Unix.Catalog.GetString("Average");
            this.hbox3.Add(this.labelAverageWeight);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox3[this.labelAverageWeight]));
            w18.PackType = ((Gtk.PackType)(1));
            w18.Position = 3;
            w18.Expand = false;
            w18.Fill = false;
            this.vbox3.Add(this.hbox3);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
            w19.Position = 1;
            w19.Expand = false;
            w19.Fill = false;
            this.GtkAlignment.Add(this.vbox3);
            this.frame1.Add(this.GtkAlignment);
            this.GtkLabel2 = new Gtk.Label();
            this.GtkLabel2.Name = "GtkLabel2";
            this.GtkLabel2.LabelProp = Mono.Unix.Catalog.GetString("<b>Weight Sensors</b>");
            this.GtkLabel2.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel2;
            this.vbox1.Add(this.frame1);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
            w22.Position = 3;
            w22.Expand = false;
            w22.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.drawingareaBalance = new Gtk.DrawingArea();
            this.drawingareaBalance.Name = "drawingareaBalance";
            this.GtkAlignment1.Add(this.drawingareaBalance);
            this.frame2.Add(this.GtkAlignment1);
            this.GtkLabel3 = new Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = Mono.Unix.Catalog.GetString("<b>Balance</b>");
            this.GtkLabel3.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel3;
            this.vbox1.Add(this.frame2);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame2]));
            w25.Position = 4;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.btnUpdateBattery = new Gtk.Button();
            this.btnUpdateBattery.CanFocus = true;
            this.btnUpdateBattery.Name = "btnUpdateBattery";
            this.btnUpdateBattery.UseUnderline = true;
            this.btnUpdateBattery.Label = Mono.Unix.Catalog.GetString("Update Battery");
            this.hbox1.Add(this.btnUpdateBattery);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.hbox1[this.btnUpdateBattery]));
            w26.Position = 0;
            w26.Expand = false;
            w26.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.progressbar1 = new Gtk.ProgressBar();
            this.progressbar1.Name = "progressbar1";
            this.hbox1.Add(this.progressbar1);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.hbox1[this.progressbar1]));
            w27.Position = 1;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w28.Position = 5;
            w28.Expand = false;
            w28.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            w1.SetUiManager(w2);
            this.Show();
            this.DisconnectAction.Activated += new System.EventHandler(this.OnDisconnectActionActivated);
            this.checkboxLed.Pressed += new System.EventHandler(this.OnCheckboxLedPressed);
            this.drawingareaBalance.ExposeEvent += new Gtk.ExposeEventHandler(this.OnDrawingareaBalanceExposeEvent);
            this.btnUpdateBattery.Pressed += new System.EventHandler(this.OnBtnUpdateBatteryPressed);
        }
    }
}
