// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LinuxGUITest {
    
    
    public partial class ClassicControllerInformation {
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label label5;
        
        private Gtk.Entry entry5;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.HBox hbox6;
        
        private Gtk.Entry entry6;
        
        private Gtk.Entry entry7;
        
        private Gtk.Label GtkLabel;
        
        private Gtk.Frame frame3;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.HBox hbox7;
        
        private Gtk.Entry entry8;
        
        private Gtk.Entry entry9;
        
        private Gtk.Label GtkLabel1;
        
        private Gtk.Frame frame4;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.HBox hbox8;
        
        private Gtk.Entry entry10;
        
        private Gtk.Entry entry11;
        
        private Gtk.Label GtkLabel2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LinuxGUITest.ClassicControllerInformation
            Stetic.BinContainer.Attach(this);
            this.Name = "LinuxGUITest.ClassicControllerInformation";
            // Container child LinuxGUITest.ClassicControllerInformation.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Buttons");
            this.hbox3.Add(this.label5);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox3[this.label5]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.entry5 = new Gtk.Entry();
            this.entry5.CanFocus = true;
            this.entry5.Name = "entry5";
            this.entry5.IsEditable = true;
            this.entry5.InvisibleChar = '●';
            this.hbox3.Add(this.entry5);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox3[this.entry5]));
            w2.Position = 1;
            this.vbox2.Add(this.hbox3);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.hbox6 = new Gtk.HBox();
            this.hbox6.Name = "hbox6";
            this.hbox6.Spacing = 6;
            // Container child hbox6.Gtk.Box+BoxChild
            this.entry6 = new Gtk.Entry();
            this.entry6.WidthRequest = 80;
            this.entry6.CanFocus = true;
            this.entry6.Name = "entry6";
            this.entry6.IsEditable = true;
            this.entry6.InvisibleChar = '●';
            this.hbox6.Add(this.entry6);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox6[this.entry6]));
            w4.Position = 0;
            w4.Expand = false;
            // Container child hbox6.Gtk.Box+BoxChild
            this.entry7 = new Gtk.Entry();
            this.entry7.WidthRequest = 80;
            this.entry7.CanFocus = true;
            this.entry7.Name = "entry7";
            this.entry7.IsEditable = true;
            this.entry7.InvisibleChar = '●';
            this.hbox6.Add(this.entry7);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox6[this.entry7]));
            w5.Position = 1;
            w5.Expand = false;
            this.GtkAlignment.Add(this.hbox6);
            this.frame2.Add(this.GtkAlignment);
            this.GtkLabel = new Gtk.Label();
            this.GtkLabel.Name = "GtkLabel";
            this.GtkLabel.LabelProp = Mono.Unix.Catalog.GetString("<b>Triggers</b>");
            this.GtkLabel.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel;
            this.vbox2.Add(this.frame2);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame2]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame3 = new Gtk.Frame();
            this.frame3.Name = "frame3";
            this.frame3.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame3.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.hbox7 = new Gtk.HBox();
            this.hbox7.Name = "hbox7";
            this.hbox7.Spacing = 6;
            // Container child hbox7.Gtk.Box+BoxChild
            this.entry8 = new Gtk.Entry();
            this.entry8.WidthRequest = 80;
            this.entry8.CanFocus = true;
            this.entry8.Name = "entry8";
            this.entry8.IsEditable = true;
            this.entry8.InvisibleChar = '●';
            this.hbox7.Add(this.entry8);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox7[this.entry8]));
            w9.Position = 0;
            w9.Expand = false;
            // Container child hbox7.Gtk.Box+BoxChild
            this.entry9 = new Gtk.Entry();
            this.entry9.WidthRequest = 80;
            this.entry9.CanFocus = true;
            this.entry9.Name = "entry9";
            this.entry9.IsEditable = true;
            this.entry9.InvisibleChar = '●';
            this.hbox7.Add(this.entry9);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox7[this.entry9]));
            w10.Position = 1;
            w10.Expand = false;
            this.GtkAlignment1.Add(this.hbox7);
            this.frame3.Add(this.GtkAlignment1);
            this.GtkLabel1 = new Gtk.Label();
            this.GtkLabel1.Name = "GtkLabel1";
            this.GtkLabel1.LabelProp = Mono.Unix.Catalog.GetString("<b>LeftStick</b>");
            this.GtkLabel1.UseMarkup = true;
            this.frame3.LabelWidget = this.GtkLabel1;
            this.vbox2.Add(this.frame3);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame3]));
            w13.Position = 2;
            w13.Expand = false;
            w13.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame4 = new Gtk.Frame();
            this.frame4.Name = "frame4";
            this.frame4.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame4.Gtk.Container+ContainerChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.hbox8 = new Gtk.HBox();
            this.hbox8.Name = "hbox8";
            this.hbox8.Spacing = 6;
            // Container child hbox8.Gtk.Box+BoxChild
            this.entry10 = new Gtk.Entry();
            this.entry10.WidthRequest = 80;
            this.entry10.CanFocus = true;
            this.entry10.Name = "entry10";
            this.entry10.IsEditable = true;
            this.entry10.InvisibleChar = '●';
            this.hbox8.Add(this.entry10);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox8[this.entry10]));
            w14.Position = 0;
            w14.Expand = false;
            // Container child hbox8.Gtk.Box+BoxChild
            this.entry11 = new Gtk.Entry();
            this.entry11.WidthRequest = 80;
            this.entry11.CanFocus = true;
            this.entry11.Name = "entry11";
            this.entry11.IsEditable = true;
            this.entry11.InvisibleChar = '●';
            this.hbox8.Add(this.entry11);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox8[this.entry11]));
            w15.Position = 1;
            w15.Expand = false;
            this.GtkAlignment2.Add(this.hbox8);
            this.frame4.Add(this.GtkAlignment2);
            this.GtkLabel2 = new Gtk.Label();
            this.GtkLabel2.Name = "GtkLabel2";
            this.GtkLabel2.LabelProp = Mono.Unix.Catalog.GetString("<b>RightStick</b>");
            this.GtkLabel2.UseMarkup = true;
            this.frame4.LabelWidget = this.GtkLabel2;
            this.vbox2.Add(this.frame4);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame4]));
            w18.Position = 3;
            w18.Expand = false;
            w18.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
