// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LinuxGUITest {
    
    
    public partial class NunchukInformation {
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label1;
        
        private Gtk.Entry entry1;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Entry entry2;
        
        private Gtk.Entry entry3;
        
        private Gtk.Label GtkLabel;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Entry entryX;
        
        private Gtk.Entry entryY;
        
        private Gtk.Entry entryZ;
        
        private Gtk.Label GtkLabel1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LinuxGUITest.NunchukInformation
            Stetic.BinContainer.Attach(this);
            this.Name = "LinuxGUITest.NunchukInformation";
            // Container child LinuxGUITest.NunchukInformation.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Buttons");
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.entry1 = new Gtk.Entry();
            this.entry1.CanFocus = true;
            this.entry1.Name = "entry1";
            this.entry1.IsEditable = true;
            this.entry1.InvisibleChar = '●';
            this.hbox1.Add(this.entry1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.entry1]));
            w2.Position = 1;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.entry2 = new Gtk.Entry();
            this.entry2.WidthRequest = 80;
            this.entry2.CanFocus = true;
            this.entry2.Name = "entry2";
            this.entry2.IsEditable = true;
            this.entry2.InvisibleChar = '●';
            this.hbox3.Add(this.entry2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox3[this.entry2]));
            w4.Position = 0;
            w4.Expand = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.entry3 = new Gtk.Entry();
            this.entry3.WidthRequest = 80;
            this.entry3.CanFocus = true;
            this.entry3.Name = "entry3";
            this.entry3.IsEditable = true;
            this.entry3.InvisibleChar = '●';
            this.hbox3.Add(this.entry3);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox3[this.entry3]));
            w5.Position = 1;
            w5.Expand = false;
            this.GtkAlignment.Add(this.hbox3);
            this.frame1.Add(this.GtkAlignment);
            this.GtkLabel = new Gtk.Label();
            this.GtkLabel.Name = "GtkLabel";
            this.GtkLabel.LabelProp = Mono.Unix.Catalog.GetString("<b>Analog Stick</b>");
            this.GtkLabel.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel;
            this.vbox1.Add(this.frame1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.entryX = new Gtk.Entry();
            this.entryX.WidthRequest = 80;
            this.entryX.CanFocus = true;
            this.entryX.Name = "entryX";
            this.entryX.IsEditable = false;
            this.entryX.InvisibleChar = '●';
            this.hbox4.Add(this.entryX);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox4[this.entryX]));
            w9.Position = 0;
            // Container child hbox4.Gtk.Box+BoxChild
            this.entryY = new Gtk.Entry();
            this.entryY.WidthRequest = 80;
            this.entryY.CanFocus = true;
            this.entryY.Name = "entryY";
            this.entryY.IsEditable = false;
            this.entryY.InvisibleChar = '●';
            this.hbox4.Add(this.entryY);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox4[this.entryY]));
            w10.Position = 1;
            // Container child hbox4.Gtk.Box+BoxChild
            this.entryZ = new Gtk.Entry();
            this.entryZ.WidthRequest = 80;
            this.entryZ.CanFocus = true;
            this.entryZ.Name = "entryZ";
            this.entryZ.IsEditable = false;
            this.entryZ.InvisibleChar = '●';
            this.hbox4.Add(this.entryZ);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox4[this.entryZ]));
            w11.Position = 2;
            this.GtkAlignment1.Add(this.hbox4);
            this.frame2.Add(this.GtkAlignment1);
            this.GtkLabel1 = new Gtk.Label();
            this.GtkLabel1.Name = "GtkLabel1";
            this.GtkLabel1.LabelProp = Mono.Unix.Catalog.GetString("<b>Accelerometers</b>");
            this.GtkLabel1.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel1;
            this.vbox1.Add(this.frame2);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame2]));
            w14.Position = 2;
            w14.Expand = false;
            w14.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
